
name: Appium Mobile Test Workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Install Android Emulator Components
        run: |
          sdkmanager --list_installed
          sdkmanager "platform-tools" "platforms;android-35" "system-images;android-35;google_apis;x86_64"
      
      - name: Create Android Virtual Device
        run: |
          echo "no" | avdmanager create avd -n test_emulator \
            -k "system-images;android-35;google_apis;x86_64" \
            --device "pixel_4"
      
      - name: Start Android Emulator
        timeout-minutes: 10
        run: |
          # Start emulator with reduced startup overhead
          emulator -avd test_emulator -no-window -no-audio -gpu swiftshader_indirect &
          
          # Wait for emulator with timeout
          timeout 300 bash -c 'until adb shell getprop sys.boot_completed; do sleep 5; done'
          
          # Verify emulator status
          adb devices
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Install Appium
        run: |
          npm install -g appium@next
          appium driver install uiautomator2
      
      - name: Start Appium Server
        run: |
          appium server -p 4723 &
          sleep 10
      
      - name: Restore Dependencies
        run: dotnet restore AppiumPractise/AppiumPractise.csproj
      
      - name: Build Project
        run: dotnet build AppiumPractise/AppiumPractise.csproj --configuration Release
      
      - name: Run Appium Tests
        env:
          APPIUM_HOST: http://127.0.0.1:4723
        run: |
          dotnet test AppiumPractise/AppiumPractise.csproj --logger trx
      
      - name: Cleanup
        if: always()
        run: |
          pkill -f appium
          pkill -f emulator
