name: Appium Mobile Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android Emulator Components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-35" "system-images;android-35;google_apis;x86_64" "emulator"
          sdkmanager --update

      - name: Create Android Virtual Device
        run: |
          echo "no" | avdmanager create avd -n test_emulator \
            -k "system-images;android-35;google_apis;x86_64" \
            --device "pixel_4" \
            --force

      - name: Verify Emulator Installation
        run: |
          $ANDROID_HOME/emulator/emulator -list-avds
          $ANDROID_HOME/emulator/emulator -accel-check

      - name: Start Android Emulator
        timeout-minutes: 15
        run: |
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export PATH=$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$PATH

          # Start emulator in background
          nohup $ANDROID_HOME/emulator/emulator -avd test_emulator \
            -no-audio \
            -no-snapshot \
            -gpu swiftshader_indirect \
            -camera-back none \
            -camera-front none \
            -no-boot-anim \
            -verbose > emulator.log 2>&1 &
          EMULATOR_PID=$!

          # Wait for emulator to start
          adb wait-for-device

          # Wait for full boot
          boot_completed=0
          for i in {1..30}; do
            boot_status=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            if [ "$boot_status" = "1" ]; then
              boot_completed=1
              break
            fi
            sleep 10
            echo "Waiting for boot to complete... ($i/30)"
          done

          if [ $boot_completed -eq 1 ]; then
            echo "Emulator booted successfully"
            adb devices
            adb shell input keyevent 82  # Unlock screen
          else
            echo "Emulator failed to boot"
            cat emulator.log
            kill $EMULATOR_PID
            exit 1
          fi

      - name: Run Tests
        run: |
          echo "Running tests..."
          # Add your Appium test command here